import { supabase } from './supabase';

export type ShippingProviderId = 'yalidine' | 'zr_express' | 'maystro' | 'noest' | 'dhd';
export type ShippingConnection = { provider: ShippingProviderId; status:'connected'|'disconnected'|'error'; last_tested_at?:string|null; last_error?:string|null; hasCredentials?:boolean };

export const SHIPPING_PROVIDERS = [
  {id:'yalidine' as const,name:'Yalidine Express',nameAr:'يالدين إكسبريس',tagline:'توصيل وطني · COD · تتبع',tone:'#dc3545',logoUrl:'/shipping-logos/yalidine.png',credentials:[{key:'apiId',label:'API ID',placeholder:'API ID من حسابك'},{key:'apiToken',label:'API Token',placeholder:'API Token من حسابك',secret:true}]},
  {id:'zr_express' as const,name:'ZR Express',nameAr:'زد آر إكسبريس',tagline:'Procolis · COD · Home / Stop Desk',tone:'#111827',logoUrl:'/shipping-logos/zr-express.png',credentials:[{key:'token',label:'Token (Legacy / Procolis)',placeholder:'Token ZR / Procolis'},{key:'key',label:'Key (Legacy / Procolis)',placeholder:'Key ZR / Procolis',secret:true},{key:'apiKey',label:'API Key (New)',placeholder:'API Key ZR',secret:true},{key:'tenantId',label:'Tenant ID (New)',placeholder:'Tenant ID ZR'}]},
  {id:'maystro' as const,name:'Maystro Delivery',nameAr:'مايسترو ديليفري',tagline:'Authentication Token · COD · تتبع',tone:'#008aff',logoUrl:'/shipping-logos/maystro.svg',credentials:[{key:'apiKey',label:'Authentication Token',placeholder:'Token من لوحة Maystro',secret:true}]},
  {id:'noest' as const,name:'NOEST Express',nameAr:'نوست إكسبريس',tagline:'API Token · GUID · Stop Desk',tone:'#a91314',logoUrl:'/shipping-logos/noest.png',credentials:[{key:'apiToken',label:'API Token',placeholder:'API Token من حساب NOEST',secret:true},{key:'guid',label:'User GUID',placeholder:'GUID الخاص بحسابك'}]},
  {id:'dhd' as const,name:'DHD Livraison',nameAr:'DHD للتوصيل',tagline:'EcoTrack · Bearer Token · COD',tone:'#0f766e',logoUrl:'/shipping-logos/dhd.png',credentials:[{key:'token',label:'API Token',placeholder:'Bearer/API Token من DHD',secret:true}]},
] as const;
export function providerMeta(id:ShippingProviderId){return SHIPPING_PROVIDERS.find(x=>x.id===id)!;}
async function authHeaders(){const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('سجّل الدخول أولاً');return {Authorization:`Bearer ${token}`,'Content-Type':'application/json'};}
export async function loadShippingConnections(storeId:string):Promise<ShippingConnection[]>{const headers=await authHeaders();const res=await fetch(`/api/shipping-connection?store_id=${encodeURIComponent(storeId)}`,{headers});const data=await res.json().catch(()=>({}));if(!res.ok||!data?.ok)throw new Error(data?.error||'تعذر تحميل شركات التوصيل');return (data.connections||[]) as ShippingConnection[];}
export async function connectShippingProvider(storeId:string,provider:ShippingProviderId,credentials:Record<string,string>){const headers=await authHeaders();const res=await fetch('/api/shipping-connection',{method:'POST',headers,body:JSON.stringify({store_id:storeId,provider,credentials})});const data=await res.json().catch(()=>({}));if(!res.ok||!data?.ok)throw new Error(data?.message||data?.error||'فشل اختبار وربط شركة التوصيل');return data as {ok:true;connected:true;message?:string};}
export async function disconnectShippingProvider(storeId:string,provider:ShippingProviderId){const headers=await authHeaders();const res=await fetch('/api/shipping-connection',{method:'DELETE',headers,body:JSON.stringify({store_id:storeId,provider})});const data=await res.json().catch(()=>({}));if(!res.ok||!data?.ok)throw new Error(data?.error||'تعذر فصل شركة التوصيل');}
