export const platformTranslations = {
  ar: {
    landing: {
      brandTag: "متجرك الإلكتروني · أبسط · أسرع", navHome: "الرئيسية", navFeatures: "المميزات", navHow: "كيف يعمل؟", navPricing: "الأسعار", navFaq: "الأسئلة الشائعة", contact: "تواصل معنا", login: "تسجيل الدخول", startFree: "ابدأ مجاناً",
      heroPill: "منصة التجارة الإلكترونية للتاجر الجزائري", heroTitle: "حوّل متابعيك إلى زبائن", heroTitle2: "ومتجرك إلى طلبات منظمة", heroDesc: "أنشئ متجرك، اعرض منتجاتك، استقبل الطلبات، وتابعها من لوحة واحدة — مع Checkout وواتساب والتوصيل والتحليلات.", discover: "اكتشف المنصة", noCommission: "0% عمولة على المبيعات", allWilayas: "توصيل إلى 58 ولاية", secure: "حماية للطلبات والبيانات", ready: "متجرك جاهز للمشاركة", anyPlace: "متجرك معك أينما كنت", onlineStore: "متجرك الإلكتروني", original: "منتجاتك كما تريد عرضها", onePlace: "كل شيء في مكان واحد.", newOrder: "طلب جديد", now: "الآن", fromAhmed: "من زبونك", confirmWhatsapp: "إرسال التفاصيل عبر واتساب",
      happyClients: "متاجر منشورة", platformRating: "منتجات منشورة", safeProducts: "زيارات المنصة", deliveryAverage: "زيارات المتاجر",
      problem: "المشكلة", problemsTitle: "هل ما زالت مبيعاتك موزعة بين المنشورات والرسائل؟", problem1: "المنتجات والأسعار تضيع بين منشورات Facebook وInstagram", problem2: "الزبون يسأل عن السعر والمقاس والمخزون أكثر من مرة", problem3: "الطلبات والعناوين تبقى موزعة بين المحادثات", problem4: "يصعب معرفة مصدر الطلبات وما الذي ينجح فعلاً", solution: "الحل", solutionTitle: "حوّل هذا المسار إلى متجر واحد مع", solutionDesc: "شارك رابط متجرك في Facebook وInstagram وWhatsApp. الزبون يختار المنتج، يملأ Checkout، يُحفظ الطلب، ثم تُرسل تفاصيله عبر واتساب.", whatsappConfirm: "الطلب محفوظ في لوحة التاجر قبل فتح واتساب",
      howTag: "كيف يعمل؟", howTitle: "من الرابط إلى الطلب في خطوات واضحة", how1: "أنشئ متجرك", how1d: "جهّز اسم المتجر وبيانات التواصل والهوية.", how2: "أضف منتجاتك", how2d: "الصور والأسعار والمخزون وVariants عند الحاجة.", how3: "استقبل الطلب", how3d: "Checkout واحد يحفظ بيانات الزبون والمنتجات والتوصيل.", how4: "أكمل عبر واتساب", how4d: "تصل تفاصيل الطلب إلى التاجر وتبقى محفوظة في اللوحة.",
      dashTag: "لوحة التاجر", dashTitle: "إدارة متجرك", dashTitle2: "من مكان واحد", dashDesc: "تابع الطلبات والمنتجات والمخزون والتسويق من لوحة واحدة بدل التنقل بين الرسائل والمنشورات.", dash1: "متابعة الطلبات والحالات", dash2: "إدارة المنتجات والمخزون وVariants", dash3: "تحليلات التسويق والإسناد", dash4: "إعدادات التوصيل وقنوات التواصل", stores: "المتاجر", products: "المنتجات", confirmed: "مؤكد", new: "جديد", shipping: "قيد التوصيل",
      featuresTag: "مميزات المنصة", featuresTitle: "الأدوات التي يحتاجها التاجر فعلاً", support: "متجر باسمك", supportD: "رابط جاهز للمشاركة على Facebook وInstagram وWhatsApp", security: "طلبات منظمة", securityD: "Checkout واحد يحفظ تفاصيل الزبون والطلب", design: "منتجات وVariants", designD: "السعر والمخزون لكل منتج أو Variant عند الحاجة", flexible: "التوصيل", flexibleD: "إعدادات وطنية أو محلية وإدارة الطلبات من اللوحة", growth: "التسويق والتحليلات", growthD: "UTM وfbclid وMeta Pixel وإسناد الطلبات عند توفر البيانات",
      pricingTag: "الأسعار", pricingTitle: "ابدأ مجاناً، وترقَّ عندما تحتاج المزيد", monthly: "شهري", yearly: "سنوي", free: "مجاني", upTo: "حتى", ordersMonth: "طلباً / شهر", whatsapp58: "واتساب + 58 ولاية", proPopular: "الأكثر طلباً", unlimited: "منتجات وطلبات بلا حد", removeBrand: "إزالة شعار المنصة", excel: "تصدير Excel للشحن", priority: "دعم أولوية", shippingPlan: "التوصيل", allPro: "كل مزايا Pro", carrier: "ربط شركات التوصيل المدعومة", tracking: "إنشاء ومتابعة الشحنات عند توفر الربط", topPriority: "أولوية قصوى للدعم", upgradePro: "ترقية Pro", proShipping: "Pro Delivery", shippingNote: "Pro Delivery يضيف أدوات الشحن المتقدمة المتاحة في حسابك إلى جانب مزايا Pro.",
      faqTag: "الأسئلة الشائعة", faqTitle: "إجابات سريعة للتاجر", q1: "هل أستطيع البدء مجاناً؟", a1: "نعم. الخطة المجانية تتيح إنشاء متجر واستقبال الطلبات ضمن حدودها وبدون عمولة على المبيعات.", q2: "هل أحتاج إلى موقع خاص؟", a2: "لا. تحصل على رابط متجر جاهز ويمكنك مشاركته مباشرة في Facebook وInstagram وWhatsApp.", q3: "كيف يصلني الطلب؟", a3: "يُحفظ الطلب في لوحة التاجر، ثم يفتح WhatsApp لإرسال تفاصيل الطلب إلى رقم المتجر.", q4: "هل أستطيع إدارة المخزون؟", a4: "نعم. يمكنك تتبع مخزون المنتجات، ومع نظام Variants يمكن إدارة المخزون لكل لون أو مقاس أو Pointure.", q5: "هل السعر يختلف حسب الـVariant؟", a5: "نعم. كل Variant يمكن أن يملك سعره ومخزونه الخاص، ويُتحقق منهما على الخادم عند إنشاء الطلب.", q6: "هل WhatsApp اختياري؟", a6: "في نموذج Dzair Store الحالي، تأكيد الطلب يتضمن فتح WhatsApp لإرسال التفاصيل بعد حفظ الطلب.", q7: "هل أستطيع معرفة مصدر الطلب؟", a7: "عند توفر بيانات UTM أو fbclid والإسناد، يمكن ربط الطلب بمصدره وحملته في أدوات التسويق.", q8: "هل توجد خطط Pro وPro Delivery؟", a8: "نعم. يمكنك البدء مجاناً ثم الترقية إلى Pro أو Pro Delivery حسب الأدوات التي تحتاجها.", finalTitle: "جاهز لبناء متجرك؟", finalDesc: "أنشئ رابط متجرك وابدأ بتحويل متابعيك إلى طلبات منظمة.", startNow: "أنشئ متجرك الآن", rights: "جميع الحقوق محفوظة", privacy: "سياسة الخصوصية", terms: "شروط الاستخدام",
    },
    store: {
      navStore: "المتجر", navExperience: "تجربتنا", navContact: "تواصل معنا", manage: "إدارة المتجر", whatsapp: "واتساب", closeMenu: "إغلاق القائمة", openMenu: "فتح القائمة", discoverProducts: "اكتشف المنتجات", featured: "مميز", choiceToday: "اختيار اليوم", productSelected: "منتج مختار بعناية، جاهز للطلب والتوصيل.", price: "السعر", cod: "✓ الدفع عند الاستلام · توصيل إلى 58 ولاية", orderNow: "اطلب المنتج الآن", delivery58: "توصيل إلى 58 ولاية", fastSafe: "سريع وآمن إلى بابك", codTitle: "الدفع عند الاستلام", payAfter: "ادفع بعد وصول طلبك", guarantee: "ضمان حقيقي", carefullySelected: "منتجات مختارة بعناية", collection: "المجموعة المختارة", collectionTitle: "أدوات يومية،", collectionTitle2: "بتنفيذ استثنائي.", discoverStore: "اكتشف منتجات المتجر واختر ما يناسبك.", addToCart: "أضف إلى السلة", experience: "من الاختيار إلى بابك", simple: "تجربة بسيطة.", fullTrust: "ثقة كاملة.", chooseProduct: "اختر منتجك", chooseProductD: "تصفّح المجموعة واعثر على القطعة المناسبة.", sendOrder: "أرسل طلبك", sendOrderD: "نموذج سريع + واتساب بتفاصيل المنتج والسعر.", receiveSafe: "استلمه بأمان", receiveSafeD: "نؤكد الطلب ونوصله إليك، والدفع عند الاستلام.", help: "هل تحتاج مساعدة؟", talk: "تحدث معنا", shopEasy: "تسوّق بكل سهولة، واطلب ما يعجبك.", workingHours: "ساعات العمل:", createStore: "أنشئ متجرك الإلكتروني بسهولة", receiving: "نستقبل الطلبات الآن", closedOrders: "المتجر مغلق — لا نستقبل طلبات الآن", ownerLogin: "دخول صاحب المتجر · لوحة التحكم", contactWhatsapp: "تواصل معنا عبر واتساب", cart: "السلة", openCart: "فتح السلة", selectedOrders: "طلباتك المختارة", emptyCart: "السلة فارغة", emptyCartD: "أضف منتجاً من المتجر وسيظهر هنا.", remove: "حذف", total: "الإجمالي", checkout: "إتمام الطلب", closeCart: "إغلاق السلة", decrease: "إنقاص الكمية", increase: "زيادة الكمية", loading: "جاري تحميل المتجر…", unavailable: "المتجر غير متاح", invalidStore: "الرابط غير صحيح أو المتجر غير منشور بعد.", backPlatform: "العودة لصفحة المنصة", preparing: "المتجر قيد الإعداد", noProducts: "لم يُضف صاحب المتجر منتجات بعد. تفقّد الرابط لاحقاً.", closed: "المتجر مغلق حالياً", closedD: "التصفح متاح — استقبال الطلبات متوقف حتى يفتح التاجر", privacy: "سياسة الخصوصية", terms: "شروط الاستخدام",
    },
    order: {
      checkout: "إتمام الطلب", productsInCart: "منتجات في السلة", order: "طلبك", close: "إغلاق", registered: "تم تسجيل طلبك بنجاح", sentToMerchant: "وصل طلبك إلى المتجر ويمكنك الآن اختيار ما تريد القيام به.", openWhatsapp: "فتح واتساب", fullName: "الاسم الكامل", namePlaceholder: "الاسم واللقب", phone: "رقم الهاتف", wilaya: "الولاية", commune: "البلدية", optional: "اختياري", neighborhood: "الحي / البلدية", cityExample: "مثلاً: وسط المدينة", address: "العنوان التفصيلي", addressPlaceholder: "الحي، الشارع، رقم المنزل", delivery: "التوصيل", home: "للمنزل", desk: "مكتب / استلام", products: "المنتجات", localDelivery: "توصيل محلي", shipping: "الشحن", total: "الإجمالي", submit: "تأكيد الطلب", submitWhatsapp: "تأكيد الطلب وفتح واتساب", nameError: "أدخل الاسم الكامل", phoneError: "أدخل رقم هاتف جزائري صحيح", storeError: "المتجر غير جاهز", closeSuccess: "العودة إلى المتجر",
    }
  },
  fr: {
    landing: {
      brandTag: "Votre boutique · Plus simple · Plus rapide", navHome: "Accueil", navFeatures: "Fonctionnalités", navHow: "Comment ça marche ?", navPricing: "Tarifs", navFaq: "FAQ", contact: "Contact", login: "Se connecter", startFree: "Commencer gratuitement",
      heroPill: "La plateforme e-commerce pensée pour les commerçants algériens", heroTitle: "Transformez vos abonnés en clients", heroTitle2: "et vos messages en commandes structurées", heroDesc: "Créez votre boutique, présentez vos produits, recevez les commandes et suivez-les depuis un seul tableau de bord — avec checkout, WhatsApp, livraison et analytics.", discover: "Découvrir la plateforme", noCommission: "0 % de commission sur les ventes", allWilayas: "Livraison dans les 58 wilayas", secure: "Protection des commandes et des données", ready: "Votre boutique prête à partager", anyPlace: "Votre boutique partout avec vous", onlineStore: "Votre boutique en ligne", original: "Vos produits, présentés comme vous le souhaitez", onePlace: "Tout au même endroit.", newOrder: "Nouvelle commande", now: "Maintenant", fromAhmed: "De votre client", confirmWhatsapp: "Envoyer les détails sur WhatsApp",
      happyClients: "Boutiques publiées", platformRating: "Produits publiés", safeProducts: "Visites de la plateforme", deliveryAverage: "Visites des boutiques",
      problem: "Le problème", problemsTitle: "Vos ventes sont encore dispersées entre publications et messages ?", problem1: "Produits et prix se perdent entre Facebook et Instagram", problem2: "Le client demande plusieurs fois le prix, la taille ou le stock", problem3: "Commandes et adresses restent dispersées dans les conversations", problem4: "Difficile de savoir d’où viennent réellement les commandes", solution: "La solution", solutionTitle: "Transformez ce parcours en une seule boutique avec", solutionDesc: "Partagez votre boutique sur Facebook, Instagram et WhatsApp. Le client choisit, passe au checkout, la commande est enregistrée puis ses détails sont envoyés sur WhatsApp.", whatsappConfirm: "La commande est enregistrée avant l’ouverture de WhatsApp",
      howTag: "Comment ça marche ?", howTitle: "Du lien à la commande en quelques étapes", how1: "Créez votre boutique", how1d: "Préparez le nom, les coordonnées et l’identité de la boutique.", how2: "Ajoutez vos produits", how2d: "Photos, prix, stock et variantes lorsque nécessaire.", how3: "Recevez la commande", how3d: "Un checkout unique enregistre le client, les produits et la livraison.", how4: "Finalisez sur WhatsApp", how4d: "Les détails arrivent au commerçant et restent dans le tableau de bord.",
      dashTag: "Tableau du commerçant", dashTitle: "Gérez votre boutique", dashTitle2: "au même endroit", dashDesc: "Suivez commandes, produits, stock et marketing depuis un seul espace au lieu de jongler entre messages et publications.", dash1: "Suivi des commandes et statuts", dash2: "Produits, stock et variantes", dash3: "Analytics marketing et attribution", dash4: "Livraison et canaux de contact", stores: "Boutiques", products: "Produits", confirmed: "Confirmée", new: "Nouvelle", shipping: "En livraison",
      featuresTag: "Fonctionnalités", featuresTitle: "Les outils dont votre commerce a vraiment besoin", support: "Une boutique à votre nom", supportD: "Un lien prêt à partager sur Facebook, Instagram et WhatsApp", security: "Commandes structurées", securityD: "Un checkout unique pour les détails du client et de la commande", design: "Produits et variantes", designD: "Prix et stock par produit ou par variante", flexible: "Livraison", flexibleD: "Livraison nationale ou locale et gestion depuis le tableau de bord", growth: "Marketing & analytics", growthD: "UTM, fbclid, Meta Pixel et attribution lorsque les données sont disponibles",
      pricingTag: "Tarifs", pricingTitle: "Commencez gratuitement, évoluez quand vous en avez besoin", monthly: "Mensuel", yearly: "Annuel", free: "Gratuit", upTo: "Jusqu’à", ordersMonth: "commandes / mois", whatsapp58: "WhatsApp + 58 wilayas", proPopular: "Le plus demandé", unlimited: "Produits et commandes illimités", removeBrand: "Retrait du logo de la plateforme", excel: "Export Excel pour la livraison", priority: "Support prioritaire", shippingPlan: "Livraison", allPro: "Tous les avantages Pro", carrier: "Connexion aux transporteurs pris en charge", tracking: "Création et suivi des expéditions lorsque la connexion est disponible", topPriority: "Priorité maximale au support", upgradePro: "Passer à Pro", proShipping: "Pro Delivery", shippingNote: "Pro Delivery ajoute les outils de livraison avancés disponibles sur votre compte, en plus des avantages Pro.",
      faqTag: "FAQ", faqTitle: "Réponses rapides pour les commerçants", q1: "Puis-je commencer gratuitement ?", a1: "Oui. Le forfait gratuit permet de créer une boutique et de recevoir des commandes dans ses limites, sans commission sur les ventes.", q2: "Ai-je besoin d’un site séparé ?", a2: "Non. Vous obtenez un lien de boutique prêt à partager sur Facebook, Instagram et WhatsApp.", q3: "Comment reçois-je une commande ?", a3: "La commande est enregistrée dans le tableau de bord, puis WhatsApp s’ouvre pour envoyer ses détails au numéro de la boutique.", q4: "Puis-je gérer le stock ?", a4: "Oui. Vous pouvez suivre le stock des produits et, avec les variantes, gérer le stock par couleur, taille ou pointure.", q5: "Le prix peut-il varier selon la variante ?", a5: "Oui. Chaque variante peut avoir son propre prix et son propre stock, vérifiés côté serveur lors de la commande.", q6: "WhatsApp est-il optionnel ?", a6: "Dans le modèle actuel de Dzair Store, la confirmation de commande enregistre d’abord la commande puis ouvre WhatsApp pour envoyer les détails.", q7: "Puis-je connaître la source d’une commande ?", a7: "Lorsque les données UTM ou fbclid sont disponibles, les outils marketing peuvent relier la commande à sa source et à sa campagne.", q8: "Existe-t-il des forfaits Pro et Pro Delivery ?", a8: "Oui. Commencez gratuitement puis passez à Pro ou Pro Delivery selon les outils dont vous avez besoin.", finalTitle: "Prêt à créer votre boutique ?", finalDesc: "Créez votre lien de boutique et transformez vos abonnés en commandes structurées.", startNow: "Créer ma boutique", rights: "Tous droits réservés", privacy: "Politique de confidentialité", terms: "Conditions d’utilisation",
    },
    store: {
      navStore: "Boutique", navExperience: "Notre expérience", navContact: "Contact", manage: "Gérer la boutique", whatsapp: "WhatsApp", closeMenu: "Fermer le menu", openMenu: "Ouvrir le menu", discoverProducts: "Découvrir les produits", featured: "À la une", choiceToday: "Choix du jour", productSelected: "Produit soigneusement sélectionné, prêt à commander et à livrer.", price: "Prix", cod: "✓ Paiement à la livraison · Livraison dans 58 wilayas", orderNow: "Commander maintenant", delivery58: "Livraison dans 58 wilayas", fastSafe: "Rapide et sûre jusqu’à votre porte", codTitle: "Paiement à la livraison", payAfter: "Payez à la réception", guarantee: "Garantie réelle", carefullySelected: "Produits soigneusement sélectionnés", collection: "Collection sélectionnée", collectionTitle: "Des essentiels,", collectionTitle2: "avec une exécution remarquable.", discoverStore: "Découvrez les produits de la boutique et choisissez ce qui vous convient.", addToCart: "Ajouter au panier", experience: "Du choix jusqu’à votre porte", simple: "Une expérience simple.", fullTrust: "Une confiance totale.", chooseProduct: "Choisissez votre produit", chooseProductD: "Parcourez la collection et trouvez la pièce idéale.", sendOrder: "Envoyez votre commande", sendOrderD: "Formulaire rapide + WhatsApp avec les détails et le prix.", receiveSafe: "Recevez-le en toute sécurité", receiveSafeD: "Nous confirmons et livrons votre commande, paiement à la livraison.", help: "Besoin d’aide ?", talk: "Parler avec nous", shopEasy: "Achetez facilement et commandez ce qui vous plaît.", workingHours: "Heures d’ouverture :", createStore: "Créez votre boutique facilement", receiving: "Nous recevons les commandes maintenant", closedOrders: "Boutique fermée — aucune commande pour le moment", ownerLogin: "Accès propriétaire · Tableau de bord", contactWhatsapp: "Nous contacter sur WhatsApp", cart: "Panier", openCart: "Ouvrir le panier", selectedOrders: "Vos articles sélectionnés", emptyCart: "Votre panier est vide", emptyCartD: "Ajoutez un produit et il apparaîtra ici.", remove: "Supprimer", total: "Total", checkout: "Passer la commande", closeCart: "Fermer le panier", decrease: "Diminuer la quantité", increase: "Augmenter la quantité", loading: "Chargement de la boutique…", unavailable: "Boutique indisponible", invalidStore: "Le lien est incorrect ou la boutique n’est pas encore publiée.", backPlatform: "Retour à la plateforme", preparing: "Boutique en préparation", noProducts: "Le propriétaire n’a pas encore ajouté de produits. Revenez plus tard.", closed: "Boutique actuellement fermée", closedD: "La navigation reste disponible — les commandes sont suspendues jusqu’à la réouverture", privacy: "Politique de confidentialité", terms: "Conditions d’utilisation",
    },
    order: {
      checkout: "Passer la commande", productsInCart: "produits dans le panier", order: "Votre commande", close: "Fermer", registered: "Commande enregistrée avec succès", sentToMerchant: "Votre commande a bien été enregistrée dans la boutique.", openWhatsapp: "Ouvrir WhatsApp", fullName: "Nom complet", namePlaceholder: "Nom et prénom", phone: "Numéro de téléphone", wilaya: "Wilaya", commune: "Commune", optional: "Facultatif", neighborhood: "Quartier / commune", cityExample: "Ex. : centre-ville", address: "Adresse détaillée", addressPlaceholder: "Quartier, rue, numéro", delivery: "Livraison", home: "À domicile", desk: "Bureau / point de retrait", products: "Produits", localDelivery: "Livraison locale", shipping: "Livraison", total: "Total", submit: "Confirmer la commande", submitWhatsapp: "Confirmer et ouvrir WhatsApp", nameError: "Saisissez votre nom complet", phoneError: "Saisissez un numéro algérien valide", storeError: "La boutique n’est pas prête", closeSuccess: "Retour à la boutique",
    }
  }
} as const;
