export const platformTranslations = {
  ar: {
    landing: {
      brandTag: "متجرك · أسهل · أسرع", navHome: "الرئيسية", navFeatures: "المميزات", navHow: "كيف يعمل؟", navPricing: "الأسعار", navFaq: "الأسئلة الشائعة", contact: "تواصل معنا", login: "تسجيل الدخول", startFree: "ابدأ مجاناً",
      heroPill: "منصة احترافية للتجارة الإلكترونية في الجزائر", heroTitle: "أنشئ متجرك وتلقَّ طلباتك", heroTitle2: "على واتساب في دقائق", heroDesc: "كل ما تحتاجه لبدء متجرك الإلكتروني: من المنتجات إلى إدارة الطلبات والشحن — في منصة واحدة، سهلة وآمنة.", discover: "اكتشف المنصة", noCommission: "بدون عمولة على المبيعات", allWilayas: "شحن وتوصيل لكل ولايات الجزائر", secure: "دفع آمن 100%", ready: "متجرك جاهز بضغطة واحدة", anyPlace: "متجرك بين يديك في أي مكان", onlineStore: "متجرك الإلكتروني", original: "منتجات أصلية بجودة عالية", onePlace: "كل شيء في مكان واحد.", newOrder: "طلب جديد", now: "الآن", fromAhmed: "من أحمد", confirmWhatsapp: "تأكيد عبر واتساب",
      happyClients: "عميل سعيد", platformRating: "تقييم المنصة", safeProducts: "منتجات آمنة", deliveryAverage: "متوسط التوصيل",
      problem: "المشكلة", problemsTitle: "هل تعاني من هذه المشاكل؟", problem1: "صعوبة العثور على منتجاتك، جودة وسعر مناسب", problem2: "القلق من جودة المنتجات والتعاملات غير الموثوقة", problem3: "تأخر التوصيل وعدم معرفة حالة الطلب", problem4: "ضياع الوقت في البحث بين مواقع كثيرة", solution: "الحل", solutionTitle: "تسوق بثقة مع", solutionDesc: "نحن نوفر لك تجربة تسوق سهلة وآمنة، من اختيار المنتج حتى استلامه في باب بيتك.", whatsappConfirm: "تأكيد الطلب عبر واتساب لضمان التواصل السريع والدقيق",
      howTag: "كيف يعمل؟", howTitle: "من طلبك إلى باب منزلك", how1: "تصفح واختر", how1d: "المنتجات التي تناسبك من متجرك", how2: "تأكيد عبر واتساب", how2d: "للتواصل معك لتأكيد الطلب والتفاصيل", how3: "تجهيز الطلب", how3d: "نؤكد طلبك ونعدّ الشحنة", how4: "شحن وتوصيل", how4d: "توصيل سريع إلى بابك في أسرع وقت",
      dashTag: "لوحة التحكم", dashTitle: "إدارة سهلة لمتجرك", dashTitle2: "في مكان واحد", dashDesc: "تابع طلباتك، أدر منتجاتك، واحصل على تقارير مفصلة — كل ذلك من لوحة تحكم بسيطة.", dash1: "متابعة الطلبات بشكل مباشر", dash2: "إدارة المنتجات والمخزون", dash3: "تقارير ومؤشرات الأداء", dash4: "إعدادات متقدمة", stores: "المتاجر", products: "المنتجات", confirmed: "مؤكد", new: "جديد", shipping: "شحن",
      featuresTag: "مميزات المنصة", featuresTitle: "كل ما يحتاجه تاجرك", support: "دعم فني متواصل", supportD: "نساعدك في كل خطوة", security: "أمان عالي", securityD: "لبياناتك وطلباتك", design: "تصميم احترافي", designD: "متجاوب مع جميع الأجهزة", flexible: "إعدادات مرنة", flexibleD: "حسب احتياجاتك", growth: "نمو أعمالك", growthD: "مع أدوات التسويق",
      pricingTag: "الأسعار", pricingTitle: "ابدأ مجاناً، ترقَّ عند الحاجة", monthly: "شهري", yearly: "سنوي", free: "مجاني", upTo: "حتى", ordersMonth: "طلباً / شهر", whatsapp58: "واتساب + 58 ولاية", proPopular: "الأكثر طلباً", unlimited: "منتجات وطلبات بلا حد", removeBrand: "إزالة شعار المنصة", excel: "تصدير Excel للشحن", priority: "دعم أولوية", shippingPlan: "توصيل", allPro: "كل مزايا Pro", carrier: "ربط Yalidine وشركات الشحن من المتجر", tracking: "إنشاء الطرد وتتبعه من الطلب", topPriority: "أولوية قصوى للدعم", upgradePro: "ترقية Pro", proShipping: "Pro شحن", shippingNote: "Pro شحن للتاجر الذي يريد إرسال الطلب إلى شركة التوصيل من اللوحة، لا عبر ملف Excel فقط.",
      faqTag: "الأسئلة الشائعة", faqTitle: "إجابات سريعة", q1: "هل أبدأ مجاناً؟", a1: "نعم. الخطة المجانية تتيح متجراً واستقبال الطلبات بدون عمولة على المبيعات.", q2: "هل تأخذون نسبة من المبيعات؟", a2: "لا. لا عمولة على المبيعات ضمن الخطط الحالية.", q3: "هل تناسب المطاعم والمتاجر؟", a3: "نعم. قائمة أطباق أو كتالوج منتجات — نفس السلة والطلب عبر واتساب.", finalTitle: "جاهز لبدء رحلتك؟", finalDesc: "انضم إلى آلاف التجار وسجّل متجرك الآن.", startNow: "ابدأ الآن", rights: "جميع الحقوق محفوظة", privacy: "سياسة الخصوصية", terms: "شروط الاستخدام",
    },
    store: {
      navStore: "المتجر", navExperience: "تجربتنا", navContact: "تواصل معنا", manage: "إدارة المتجر", whatsapp: "واتساب", closeMenu: "إغلاق القائمة", openMenu: "فتح القائمة", discoverProducts: "اكتشف المنتجات", featured: "مميز", choiceToday: "اختيار اليوم", productSelected: "منتج مختار بعناية، جاهز للطلب والتوصيل.", price: "السعر", cod: "✓ الدفع عند الاستلام · توصيل إلى 58 ولاية", orderNow: "اطلب المنتج الآن", delivery58: "توصيل إلى 58 ولاية", fastSafe: "سريع وآمن إلى بابك", codTitle: "الدفع عند الاستلام", payAfter: "ادفع بعد وصول طلبك", guarantee: "ضمان حقيقي", carefullySelected: "منتجات مختارة بعناية", collection: "المجموعة المختارة", collectionTitle: "أدوات يومية،", collectionTitle2: "بتنفيذ استثنائي.", discoverStore: "اكتشف منتجات المتجر واختر ما يناسبك.", addToCart: "أضف إلى السلة", experience: "من الاختيار إلى بابك", simple: "تجربة بسيطة.", fullTrust: "ثقة كاملة.", chooseProduct: "اختر منتجك", chooseProductD: "تصفّح المجموعة واعثر على القطعة المناسبة.", sendOrder: "أرسل طلبك", sendOrderD: "نموذج سريع + واتساب بتفاصيل المنتج والسعر.", receiveSafe: "استلمه بأمان", receiveSafeD: "نؤكد الطلب ونوصله إليك، والدفع عند الاستلام.", help: "هل تحتاج مساعدة؟", talk: "تحدث معنا", shopEasy: "تسوّق بكل سهولة، واطلب ما يعجبك.", workingHours: "ساعات العمل:", createStore: "أنشئ متجرك الإلكتروني بسهولة", receiving: "نستقبل الطلبات الآن", closedOrders: "المتجر مغلق — لا نستقبل طلبات الآن", ownerLogin: "دخول صاحب المتجر · لوحة التحكم", contactWhatsapp: "تواصل معنا عبر واتساب", cart: "السلة", openCart: "فتح السلة", selectedOrders: "طلباتك المختارة", emptyCart: "السلة فارغة", emptyCartD: "أضف منتجاً من المتجر وسيظهر هنا.", remove: "حذف", total: "الإجمالي", checkout: "إتمام الطلب", closeCart: "إغلاق السلة", decrease: "إنقاص الكمية", increase: "زيادة الكمية", loading: "جاري تحميل المتجر…", unavailable: "المتجر غير متاح", invalidStore: "الرابط غير صحيح أو المتجر غير منشور بعد.", backPlatform: "العودة لصفحة المنصة", preparing: "المتجر قيد الإعداد", noProducts: "لم يُضف صاحب المتجر منتجات بعد. تفقّد الرابط لاحقاً.", closed: "المتجر مغلق حالياً", closedD: "التصفح متاح — استقبال الطلبات متوقف حتى يفتح التاجر", privacy: "سياسة الخصوصية", terms: "شروط الاستخدام",
    },
    order: {
      checkout: "إتمام الطلب", productsInCart: "منتجات في السلة", order: "طلبك", close: "إغلاق", registered: "تم تسجيل طلبك", sentToMerchant: "وصل للتاجر على واتساب وفي لوحة المتجر.", openWhatsapp: "فتح واتساب مرة أخرى", fullName: "الاسم الكامل", namePlaceholder: "الاسم واللقب", phone: "رقم الهاتف", wilaya: "الولاية", commune: "البلدية", optional: "اختياري", neighborhood: "الحي / البلدية", cityExample: "مثلاً: وسط المدينة", address: "العنوان التفصيلي", addressPlaceholder: "الحي، الشارع، رقم المنزل", delivery: "التوصيل", home: "للمنزل", desk: "مكتب / استلام", products: "المنتجات", localDelivery: "توصيل محلي", shipping: "الشحن", total: "الإجمالي", submit: "تأكيد الطلب", submitWhatsapp: "تأكيد الطلب وفتح واتساب", nameError: "أدخل الاسم الكامل", phoneError: "أدخل رقم هاتف جزائري صحيح", storeError: "المتجر غير جاهز", closeSuccess: "إغلاق",
    }
  },
  fr: {
    landing: {
      brandTag: "Votre boutique · Plus simple · Plus rapide", navHome: "Accueil", navFeatures: "Fonctionnalités", navHow: "Comment ça marche ?", navPricing: "Tarifs", navFaq: "FAQ", contact: "Contact", login: "Se connecter", startFree: "Commencer gratuitement",
      heroPill: "Plateforme e-commerce professionnelle en Algérie", heroTitle: "Créez votre boutique et recevez vos commandes", heroTitle2: "sur WhatsApp en quelques minutes", heroDesc: "Tout ce qu’il vous faut pour lancer votre boutique : produits, commandes et livraison — dans une plateforme simple et sécurisée.", discover: "Découvrir la plateforme", noCommission: "Aucune commission sur les ventes", allWilayas: "Livraison dans toutes les wilayas d’Algérie", secure: "Paiement 100 % sécurisé", ready: "Votre boutique prête en un clic", anyPlace: "Votre boutique dans votre poche", onlineStore: "Votre boutique en ligne", original: "Des produits de qualité", onePlace: "Tout au même endroit.", newOrder: "Nouvelle commande", now: "Maintenant", fromAhmed: "D’Ahmed", confirmWhatsapp: "Confirmer sur WhatsApp",
      happyClients: "Clients satisfaits", platformRating: "Note de la plateforme", safeProducts: "Produits sûrs", deliveryAverage: "Délai moyen de livraison",
      problem: "Le problème", problemsTitle: "Vous rencontrez ces problèmes ?", problem1: "Difficulté à trouver les bons produits au bon prix", problem2: "Inquiétude sur la qualité et la fiabilité", problem3: "Retards de livraison et manque de visibilité", problem4: "Temps perdu entre de nombreux sites", solution: "La solution", solutionTitle: "Achetez en confiance avec", solutionDesc: "Nous vous offrons une expérience d’achat simple et sûre, du choix du produit jusqu’à votre porte.", whatsappConfirm: "Confirmation par WhatsApp pour un échange rapide et précis",
      howTag: "Comment ça marche ?", howTitle: "De la commande à votre porte", how1: "Parcourez et choisissez", how1d: "Les produits qui vous conviennent", how2: "Confirmation sur WhatsApp", how2d: "Pour confirmer la commande et les détails", how3: "Préparation", how3d: "Nous confirmons et préparons votre colis", how4: "Expédition et livraison", how4d: "Livraison rapide jusqu’à votre porte",
      dashTag: "Tableau de bord", dashTitle: "Gérez facilement votre boutique", dashTitle2: "au même endroit", dashDesc: "Suivez vos commandes, gérez vos produits et consultez vos rapports depuis un tableau de bord simple.", dash1: "Suivi des commandes en direct", dash2: "Gestion des produits et du stock", dash3: "Rapports et indicateurs", dash4: "Paramètres avancés", stores: "Boutiques", products: "Produits", confirmed: "Confirmée", new: "Nouvelle", shipping: "Expédition",
      featuresTag: "Fonctionnalités", featuresTitle: "Tout ce dont votre commerce a besoin", support: "Support continu", supportD: "Nous vous accompagnons à chaque étape", security: "Haute sécurité", securityD: "Pour vos données et vos commandes", design: "Design professionnel", designD: "Adapté à tous les appareils", flexible: "Paramètres flexibles", flexibleD: "Selon vos besoins", growth: "Développez votre activité", growthD: "Avec des outils marketing",
      pricingTag: "Tarifs", pricingTitle: "Commencez gratuitement, évoluez quand vous voulez", monthly: "Mensuel", yearly: "Annuel", free: "Gratuit", upTo: "Jusqu’à", ordersMonth: "commandes / mois", whatsapp58: "WhatsApp + 58 wilayas", proPopular: "Le plus demandé", unlimited: "Produits et commandes illimités", removeBrand: "Retrait du logo de la plateforme", excel: "Export Excel pour la livraison", priority: "Support prioritaire", shippingPlan: "Livraison", allPro: "Tous les avantages Pro", carrier: "Connexion à Yalidine et aux sociétés de livraison", tracking: "Création et suivi des colis", topPriority: "Priorité maximale au support", upgradePro: "Passer à Pro", proShipping: "Pro Livraison", shippingNote: "Pro Livraison pour envoyer les commandes aux sociétés de livraison depuis le tableau de bord, sans se limiter à Excel.",
      faqTag: "FAQ", faqTitle: "Réponses rapides", q1: "Puis-je commencer gratuitement ?", a1: "Oui. Le forfait gratuit permet de créer une boutique et de recevoir des commandes sans commission sur les ventes.", q2: "Prenez-vous une commission sur les ventes ?", a2: "Non. Les forfaits actuels n’appliquent aucune commission sur les ventes.", q3: "Convient-il aux restaurants et aux boutiques ?", a3: "Oui. Menu ou catalogue produits — même panier et commande via WhatsApp.", finalTitle: "Prêt à commencer ?", finalDesc: "Rejoignez les commerçants et créez votre boutique maintenant.", startNow: "Commencer maintenant", rights: "Tous droits réservés", privacy: "Politique de confidentialité", terms: "Conditions d’utilisation", privacy: "Politique de confidentialité", terms: "Conditions d’utilisation",
    },
    store: {
      navStore: "Boutique", navExperience: "Notre expérience", navContact: "Contact", manage: "Gérer la boutique", whatsapp: "WhatsApp", closeMenu: "Fermer le menu", openMenu: "Ouvrir le menu", discoverProducts: "Découvrir les produits", featured: "À la une", choiceToday: "Choix du jour", productSelected: "Produit soigneusement sélectionné, prêt à commander et à livrer.", price: "Prix", cod: "✓ Paiement à la livraison · Livraison dans 58 wilayas", orderNow: "Commander maintenant", delivery58: "Livraison dans 58 wilayas", fastSafe: "Rapide et sûre jusqu’à votre porte", codTitle: "Paiement à la livraison", payAfter: "Payez à la réception", guarantee: "Garantie réelle", carefullySelected: "Produits soigneusement sélectionnés", collection: "Collection sélectionnée", collectionTitle: "Des essentiels,", collectionTitle2: "avec une exécution remarquable.", discoverStore: "Découvrez les produits de la boutique et choisissez ce qui vous convient.", addToCart: "Ajouter au panier", experience: "Du choix jusqu’à votre porte", simple: "Une expérience simple.", fullTrust: "Une confiance totale.", chooseProduct: "Choisissez votre produit", chooseProductD: "Parcourez la collection et trouvez la pièce idéale.", sendOrder: "Envoyez votre commande", sendOrderD: "Formulaire rapide + WhatsApp avec les détails et le prix.", receiveSafe: "Recevez-le en toute sécurité", receiveSafeD: "Nous confirmons et livrons votre commande, paiement à la livraison.", help: "Besoin d’aide ?", talk: "Parler avec nous", shopEasy: "Achetez facilement et commandez ce qui vous plaît.", workingHours: "Heures d’ouverture :", createStore: "Créez votre boutique facilement", receiving: "Nous recevons les commandes maintenant", closedOrders: "Boutique fermée — aucune commande pour le moment", ownerLogin: "Accès propriétaire · Tableau de bord", contactWhatsapp: "Nous contacter sur WhatsApp", cart: "Panier", openCart: "Ouvrir le panier", selectedOrders: "Vos articles sélectionnés", emptyCart: "Votre panier est vide", emptyCartD: "Ajoutez un produit et il apparaîtra ici.", remove: "Supprimer", total: "Total", checkout: "Passer la commande", closeCart: "Fermer le panier", decrease: "Diminuer la quantité", increase: "Augmenter la quantité", loading: "Chargement de la boutique…", unavailable: "Boutique indisponible", invalidStore: "Le lien est incorrect ou la boutique n’est pas encore publiée.", backPlatform: "Retour à la plateforme", preparing: "Boutique en préparation", noProducts: "Le propriétaire n’a pas encore ajouté de produits. Revenez plus tard.", closed: "Boutique actuellement fermée", closedD: "La navigation reste disponible — les commandes sont suspendues jusqu’à la réouverture", privacy: "Politique de confidentialité", terms: "Conditions d’utilisation",
    },
    order: {
      checkout: "Passer la commande", productsInCart: "produits dans le panier", order: "Votre commande", close: "Fermer", registered: "Commande enregistrée", sentToMerchant: "Elle a été envoyée au commerçant sur WhatsApp et dans son tableau de bord.", openWhatsapp: "Ouvrir WhatsApp à nouveau", fullName: "Nom complet", namePlaceholder: "Nom et prénom", phone: "Numéro de téléphone", wilaya: "Wilaya", commune: "Commune", optional: "Facultatif", neighborhood: "Quartier / commune", cityExample: "Ex. : centre-ville", address: "Adresse détaillée", addressPlaceholder: "Quartier, rue, numéro", delivery: "Livraison", home: "À domicile", desk: "Bureau / point de retrait", products: "Produits", localDelivery: "Livraison locale", shipping: "Livraison", total: "Total", submit: "Confirmer la commande", submitWhatsapp: "Confirmer et ouvrir WhatsApp", nameError: "Saisissez votre nom complet", phoneError: "Saisissez un numéro algérien valide", storeError: "La boutique n’est pas prête", closeSuccess: "Fermer",
    }
  }
} as const;
