import { createFileRoute } from "@tanstack/react-router";
import { getLanguage } from "@/i18n";
import { LegalPage, type LegalSection } from "@/components/LegalPage";

export const Route = createFileRoute("/privacy")({
  head: () => ({ meta: [
    { title: "سياسة الخصوصية | Dzair Store" },
    { name: "description", content: "سياسة الخصوصية لمنصة Dzair Store." },
  ] }),
  component: Privacy,
});

function Privacy() {
  const fr = getLanguage() === "fr";
  const sections: LegalSection[] = fr ? [
    { title: "1. Qui sommes-nous ?", paragraphs: ["Dzair Store est une plateforme de commerce social destinée aux commerçants et clients en Algérie. Elle permet de créer une boutique, présenter des produits et recevoir des commandes, notamment via WhatsApp."] },
    { title: "2. Données que nous traitons", paragraphs: ["Selon l’utilisation du service, nous pouvons traiter les informations nécessaires au compte et à la boutique, ainsi que les données fournies lors d’une commande."], bullets: ["Compte et boutique : e-mail, identité du compte, nom de la boutique, numéro WhatsApp, liens sociaux et paramètres.", "Commande : nom du client, téléphone, wilaya, commune, adresse, produits, quantités, livraison, montant, statut et informations de suivi.", "Paiements d’abonnement : informations fournies pour la vérification manuelle d’un paiement, y compris reçu téléversé, numéro d’opération, code de retrait et téléphone lorsqu’ils sont fournis.", "Marketing et attribution : paramètres UTM, fbclid, session d’attribution, page d’arrivée et produit d’arrivée lorsqu’ils sont disponibles.", "Données techniques et statistiques : visites et événements nécessaires au fonctionnement, à la mesure et à l’amélioration de la plateforme."] },
    { title: "3. Pourquoi ces données sont utilisées", paragraphs: ["Nous utilisons ces données pour fournir le service, traiter et suivre les commandes, permettre au commerçant de gérer sa boutique, vérifier les abonnements, sécuriser les opérations, mesurer l’activité et améliorer l’expérience."] },
    { title: "4. Commandes et données des clients", paragraphs: ["Lorsque vous passez une commande dans une boutique, les informations nécessaires à l’exécution de la commande sont transmises au commerçant concerné. Le commerçant est responsable de l’utilisation des données qu’il reçoit pour ses propres opérations commerciales et de livraison."] },
    { title: "5. WhatsApp et réseaux sociaux", paragraphs: ["Certaines boutiques utilisent WhatsApp ou des réseaux sociaux comme canaux de contact. Lorsque vous choisissez d’ouvrir WhatsApp ou un réseau externe, vous quittez le contrôle technique de Dzair Store et les conditions de confidentialité du service externe peuvent s’appliquer."] },
    { title: "6. Cookies, attribution et publicité", paragraphs: ["Dzair Store peut utiliser des identifiants de session et des paramètres de campagne tels que UTM et fbclid pour comprendre l’origine d’une visite et relier une commande à une campagne lorsque cette information est disponible. La plateforme et certains commerçants peuvent également utiliser Meta Pixel conformément à leur configuration."] },
    { title: "7. Stockage et sécurité", paragraphs: ["Les images publiques de produits sont stockées dans un espace destiné à être accessible depuis les boutiques publiques. Les reçus de paiement des abonnements sont stockés dans un espace privé et leur accès utilise des liens temporaires signés. Les accès aux commandes et aux données de compte sont protégés par des contrôles d’accès et des politiques RLS côté base de données."] },
    { title: "8. CAPTCHA et prévention des abus", paragraphs: ["La création d’une commande passe par une vérification CAPTCHA Turnstile afin de réduire les abus automatisés. Cette vérification est une mesure de sécurité et ne remplace pas les contrôles d’accès aux données."] },
    { title: "9. Conservation et suppression", paragraphs: ["La durée de conservation dépend de la nature de la donnée et de la nécessité de fournir le service, de gérer les commandes, la facturation, la sécurité et les obligations applicables. Le système ne définit pas actuellement une durée unique pour toutes les catégories de données. Une demande de suppression peut être étudiée selon la nature des données et les obligations applicables."] },
    { title: "10. Vos droits et vos demandes", paragraphs: ["Vous pouvez demander des informations sur les données associées à votre compte ou boutique et demander leur correction ou leur suppression lorsque cela est applicable. Certaines données peuvent devoir être conservées lorsqu’elles sont nécessaires à une commande, à la sécurité, à la facturation ou à une obligation légale."] },
    { title: "11. Modifications", paragraphs: ["Cette politique peut être mise à jour lorsque les fonctionnalités ou les traitements de données évoluent. La date de mise à jour affichée en haut de cette page indique la version publiée."] },
  ] : [
    { title: "1. من نحن؟", paragraphs: ["Dzair Store هي منصة تجارة اجتماعية موجهة للتجار والزبائن في الجزائر. تتيح إنشاء متجر، عرض المنتجات واستقبال الطلبات، بما في ذلك عبر واتساب."] },
    { title: "2. البيانات التي نعالجها", paragraphs: ["بحسب طريقة استخدام الخدمة، قد نعالج البيانات اللازمة للحساب والمتجر، إضافة إلى البيانات التي يقدمها العميل عند إنشاء طلب."], bullets: ["الحساب والمتجر: البريد الإلكتروني، هوية الحساب، اسم المتجر، رقم واتساب، روابط التواصل والإعدادات.", "الطلب: اسم العميل، الهاتف، الولاية، البلدية، العنوان، المنتجات، الكميات، التوصيل، المبلغ، الحالة ومعلومات التتبع.", "مدفوعات الاشتراك: المعلومات المقدمة للتحقق اليدوي من الدفع، ومنها صورة الوصل ورقم العملية ورمز السحب ورقم الهاتف عند تقديمها.", "التسويق والإسناد: UTM وfbclid ومعرّف جلسة الإسناد وصفحة الهبوط والمنتج الذي بدأت منه الزيارة عند توفرها.", "البيانات التقنية والإحصائية: الزيارات والأحداث اللازمة لتشغيل المنصة وقياس نشاطها وتحسين التجربة."] },
    { title: "3. لماذا نستخدم هذه البيانات؟", paragraphs: ["نستخدم البيانات لتقديم الخدمة، معالجة الطلبات ومتابعتها، تمكين التاجر من إدارة متجره، التحقق من الاشتراكات، حماية العمليات، قياس النشاط وتحسين تجربة الاستخدام."] },
    { title: "4. الطلبات وبيانات الزبائن", paragraphs: ["عند إنشاء طلب في متجر، تُرسل البيانات اللازمة لتنفيذ الطلب إلى التاجر المعني. ويكون التاجر مسؤولًا عن استخدام البيانات التي يستلمها في عملياته التجارية والتوصيل الخاصة به."] },
    { title: "5. واتساب وشبكات التواصل", paragraphs: ["قد تستخدم بعض المتاجر واتساب أو شبكات التواصل كقنوات اتصال. عند اختيار فتح واتساب أو خدمة خارجية، تنتقل من التحكم التقني المباشر لـ Dzair Store، وقد تنطبق سياسة الخصوصية الخاصة بالخدمة الخارجية."] },
    { title: "6. الإسناد والتسويق والإعلانات", paragraphs: ["قد تستخدم Dzair Store معرّفات الجلسات ومعطيات الحملات مثل UTM وfbclid لفهم مصدر الزيارة وربط الطلب بحملة عندما تتوفر هذه المعلومات. كما يمكن للمنصة وبعض التجار استخدام Meta Pixel وفق إعداداتهم."] },
    { title: "7. التخزين والحماية", paragraphs: ["تُخزن صور المنتجات العامة في مساحة مخصصة لتكون قابلة للوصول من المتاجر العامة. أما إيصالات دفع الاشتراكات فتُخزن في مساحة خاصة ويستخدم الوصول إليها روابط موقعة مؤقتة. كما تحمي سياسات RLS وضوابط الصلاحيات الوصول إلى الطلبات وبيانات الحساب."] },
    { title: "8. CAPTCHA ومنع إساءة الاستخدام", paragraphs: ["يمر إنشاء الطلب عبر تحقق CAPTCHA باستخدام Turnstile للحد من الإساءة الآلية. وهذا الإجراء أمني ولا يحل محل ضوابط الوصول إلى البيانات."] },
    { title: "9. الاحتفاظ والحذف", paragraphs: ["تختلف مدة الاحتفاظ حسب نوع البيانات والحاجة إلى تقديم الخدمة وإدارة الطلبات والفوترة والأمان والالتزامات المطبقة. لا يحدد النظام حاليًا مدة موحدة لكل فئات البيانات. يمكن دراسة طلب حذف البيانات بحسب طبيعتها والالتزامات المطبقة."] },
    { title: "10. حقوقك وطلباتك", paragraphs: ["يمكنك طلب معلومات عن البيانات المرتبطة بحسابك أو متجرك وطلب تصحيحها أو حذفها عندما يكون ذلك ممكنًا. وقد يلزم الاحتفاظ ببعض البيانات عندما تكون ضرورية لطلب أو للأمان أو للفوترة أو لالتزام قانوني."] },
    { title: "11. التعديلات", paragraphs: ["قد نحدّث هذه السياسة عند تغير وظائف المنصة أو طرق معالجة البيانات. ويبين تاريخ التحديث في أعلى الصفحة النسخة المنشورة."] },
  ];
  return <LegalPage kind="privacy" title={fr ? "Politique de confidentialité" : "سياسة الخصوصية"} intro={fr ? "Cette page décrit, de manière pratique, les données traitées par Dzair Store et les principales mesures de protection utilisées par la plateforme." : "توضح هذه الصفحة بشكل عملي البيانات التي تعالجها Dzair Store وأهم إجراءات الحماية المستخدمة في المنصة."} updated={fr ? "Dernière mise à jour : 5 octobre 2026" : "آخر تحديث: 5 أكتوبر 2026"} sections={sections} />;
}
