import { useMemo, useState } from "react";
import { ArrowUpRight, BadgePercent, Calculator, ChartNoAxesCombined, CircleDollarSign, Plus, Search, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";

type Lang = "ar" | "fr";
type Candidate = { id: number; name: string; category: string; cost: number; price: number; delivery: number; ads: number; returnRate: number; demand: number; competition: number; confidence: "manual" | "sample" };
const initial: Candidate[] = [
  { id: 1, name: "منظّم المطبخ متعدد الطبقات", category: "المنزل", cost: 900, price: 2490, delivery: 600, ads: 250, returnRate: 12, demand: 72, competition: 48, confidence: "sample" },
  { id: 2, name: "مصباح LED قابل للشحن", category: "الإلكترونيات", cost: 1200, price: 2990, delivery: 600, ads: 350, returnRate: 15, demand: 66, competition: 62, confidence: "sample" },
  { id: 3, name: "حقيبة تنظيم السفر", category: "الإكسسوارات", cost: 750, price: 2190, delivery: 600, ads: 220, returnRate: 9, demand: 58, competition: 35, confidence: "sample" },
];
const money = (n: number) => new Intl.NumberFormat("fr-DZ", { maximumFractionDigits: 0 }).format(n) + " دج";
export default function ProductRadar({ language }: { language: Lang }) {
  const fr = language === "fr";
  const [items, setItems] = useState(initial);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("all");
  const [selected, setSelected] = useState(1);
  const [showForm, setShowForm] = useState(false);
  const [draft, setDraft] = useState({ name: "", category: "المنزل", cost: "", price: "", delivery: "600", ads: "250", returnRate: "10", demand: "50", competition: "50" });
  const copy = fr ? {
    kicker: "PRODUCT INTELLIGENCE", title: "Radar de produits", intro: "Évaluez la marge et le potentiel avant d’investir dans le stock ou la publicité.", search: "Rechercher un produit", all: "Toutes les catégories", home: "Maison", tech: "Électronique", accessories: "Accessoires", add: "Ajouter une analyse", demand: "Demande estimée", competition: "Concurrence estimée", margin: "Marge nette estimée", roi: "Marge / prix", candidates: "Pistes à évaluer", formula: "Simulateur de rentabilité", cost: "Coût d’achat", price: "Prix de vente", delivery: "Livraison payée par le vendeur", ads: "Publicité par commande", returns: "Taux de retour (%)", demandLabel: "Demande (0–100)", competitionLabel: "Concurrence (0–100)", save: "Ajouter à mes analyses", cancel: "Annuler", sample: "Exemple de démonstration — pas une donnée de marché en direct", manual: "Saisie manuelle", score: "Score indicatif", net: "Profit estimé par commande livrée", breakEven: "Coût total avant retours", warning: "Hypothèses à confirmer", noResults: "Aucun produit ne correspond.", required: "Ajoutez un nom et des montants valides.", signal: "Indice exploratoire", noLive: "Aucune source de tendance connectée pour l’instant. Les scores ne sont pas des statistiques de ventes réelles.", select: "Analyser"
  } : {
    kicker: "ذكاء المنتجات", title: "رادار المنتجات", intro: "قيّم هامش الربح وفرصة المنتج قبل الاستثمار في المخزون أو الإعلانات.", search: "ابحث عن منتج", all: "كل الفئات", home: "المنزل", tech: "الإلكترونيات", accessories: "الإكسسوارات", add: "إضافة تحليل", demand: "الطلب التقديري", competition: "المنافسة التقديرية", margin: "صافي الربح التقديري", roi: "الربح من السعر", candidates: "فرص تستحق التقييم", formula: "حاسبة الربحية", cost: "سعر الشراء", price: "سعر البيع", delivery: "التوصيل على البائع", ads: "الإعلانات لكل طلب", returns: "نسبة الإرجاع (%)", demandLabel: "الطلب (0–100)", competitionLabel: "المنافسة (0–100)", save: "أضف إلى تحليلاتي", cancel: "إلغاء", sample: "أمثلة توضيحية — ليست بيانات سوق مباشرة", manual: "إدخال يدوي", score: "مؤشر إرشادي", net: "الربح المتوقع لكل طلب مسلّم", breakEven: "التكلفة قبل المرتجعات", warning: "تحتاج الفرضيات إلى التحقق", noResults: "لا توجد منتجات مطابقة.", required: "أدخل اسمًا ومبالغ صحيحة.", signal: "مؤشر استكشافي", noLive: "لا يوجد مصدر اتجاهات متصل حاليًا. المؤشرات ليست إحصاءات مبيعات فعلية.", select: "حلّل"
  };
  const visible = useMemo(() => items.filter((p) => p.name.toLowerCase().includes(query.toLowerCase()) && (category === "all" || p.category === category)), [items, query, category]);
  const selectedItem = items.find((p) => p.id === selected) || visible[0] || items[0];
  const calc = (p: Candidate) => {
    const expectedReturnCost = p.delivery * (Math.max(0, Math.min(100, p.returnRate)) / 100);
    const net = p.price - p.cost - p.delivery - p.ads - expectedReturnCost;
    const margin = p.price > 0 ? net / p.price * 100 : 0;
    const score = Math.round(p.demand * .45 + (100 - p.competition) * .30 + Math.max(0, Math.min(100, margin * 2.5)) * .25);
    return { net, margin, score };
  };
  const addCandidate = () => {
    const cost = Number(draft.cost), price = Number(draft.price);
    if (!draft.name.trim() || !Number.isFinite(cost) || !Number.isFinite(price) || cost < 0 || price <= 0) return;
    const item: Candidate = { id: Date.now(), name: draft.name.trim(), category: draft.category, cost, price, delivery: Math.max(0, Number(draft.delivery) || 0), ads: Math.max(0, Number(draft.ads) || 0), returnRate: Math.max(0, Math.min(100, Number(draft.returnRate) || 0)), demand: Math.max(0, Math.min(100, Number(draft.demand) || 0)), competition: Math.max(0, Math.min(100, Number(draft.competition) || 0)), confidence: "manual" };
    setItems((old) => [item, ...old]); setSelected(item.id); setQuery(""); setCategory("all"); setShowForm(false); setDraft({ name: "", category: "المنزل", cost: "", price: "", delivery: "600", ads: "250", returnRate: "10", demand: "50", competition: "50" });
  };
  const result = selectedItem ? calc(selectedItem) : { net: 0, margin: 0, score: 0 };
  const categories = [{ value: "all", label: copy.all }, { value: "المنزل", label: copy.home }, { value: "الإلكترونيات", label: copy.tech }, { value: "الإكسسوارات", label: copy.accessories }];
  const Field = ({ label, value, onChange, type = "number" }: { label: string; value: string; onChange: (v: string) => void; type?: string }) => <label className="radar-field"><span>{label}</span><input type={type} min={type === "number" ? 0 : undefined} value={value} onChange={(e) => onChange(e.target.value)} /></label>;
  return <div className="ab-content radar-page">
    <header className="radar-hero"><div><span className="radar-kicker"><Sparkles size={14}/>{copy.kicker}</span><h2>{copy.title}</h2><p>{copy.intro}</p><small><ShieldCheck size={14}/>{copy.sample}</small></div><div className="radar-orb"><ChartNoAxesCombined size={34}/></div></header>
    <div className="radar-notice"><TrendingUp size={17}/><span>{copy.noLive}</span></div>
    <div className="radar-toolbar"><label className="radar-search"><Search size={17}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={copy.search}/></label><select value={category} onChange={(e) => setCategory(e.target.value)}>{categories.map((c) => <option key={c.value} value={c.value}>{c.label}</option>)}</select><button className="primary-btn" onClick={() => setShowForm((v) => !v)}><Plus size={16}/>{copy.add}</button></div>
    {showForm && <section className="panel radar-form"><div className="panel-head"><h3>{copy.manual}</h3><button className="secondary-btn" onClick={() => setShowForm(false)}>{copy.cancel}</button></div><div className="radar-form-grid"><Field label={fr ? "Nom du produit" : "اسم المنتج"} type="text" value={draft.name} onChange={(v) => setDraft({ ...draft, name: v })}/><label className="radar-field"><span>{fr ? "Catégorie" : "الفئة"}</span><select value={draft.category} onChange={(e) => setDraft({ ...draft, category: e.target.value })}>{categories.slice(1).map((c) => <option key={c.value} value={c.value}>{c.label}</option>)}</select></label><Field label={copy.cost} value={draft.cost} onChange={(v) => setDraft({ ...draft, cost: v })}/><Field label={copy.price} value={draft.price} onChange={(v) => setDraft({ ...draft, price: v })}/><Field label={copy.delivery} value={draft.delivery} onChange={(v) => setDraft({ ...draft, delivery: v })}/><Field label={copy.ads} value={draft.ads} onChange={(v) => setDraft({ ...draft, ads: v })}/><Field label={copy.returns} value={draft.returnRate} onChange={(v) => setDraft({ ...draft, returnRate: v })}/><Field label={copy.demandLabel} value={draft.demand} onChange={(v) => setDraft({ ...draft, demand: v })}/><Field label={copy.competitionLabel} value={draft.competition} onChange={(v) => setDraft({ ...draft, competition: v })}/></div><button className="primary-btn" onClick={addCandidate}>{copy.save}</button></section>}
    <div className="radar-layout"><section className="panel radar-list"><div className="panel-head"><div><span className="ab-kicker">RADAR</span><h3>{copy.candidates}</h3></div><BadgePercent size={20}/></div>{visible.length === 0 && <p className="radar-empty">{copy.noResults}</p>}{visible.map((p) => { const r = calc(p); return <button key={p.id} className={`radar-product ${selectedItem?.id === p.id ? "active" : ""}`} onClick={() => setSelected(p.id)}><div className="radar-product-icon"><CircleDollarSign size={20}/></div><div className="radar-product-main"><b>{p.name}</b><small>{p.category} · {p.confidence === "sample" ? copy.sample : copy.manual}</small><span>{money(r.net)} <em>{copy.net}</em></span></div><div className="radar-score"><strong>{r.score}</strong><small>{copy.score}</small></div></button>; })}</section>
      <section className="panel radar-detail"><div className="panel-head"><div><span className="ab-kicker">{copy.signal}</span><h3>{selectedItem?.name || copy.noResults}</h3></div><Calculator size={21}/></div>{selectedItem && <><div className="radar-kpis"><div><span>{copy.demand}</span><strong>{selectedItem.demand}/100</strong><i><b style={{ width: `${selectedItem.demand}%` }}/></i></div><div><span>{copy.competition}</span><strong>{selectedItem.competition}/100</strong><i><b style={{ width: `${selectedItem.competition}%` }}/></i></div></div><div className="radar-profit"><span>{copy.margin}</span><strong className={result.net < 0 ? "negative" : ""}>{money(result.net)}</strong><small>{result.margin.toFixed(1)}% · {copy.roi}</small></div><div className="radar-breakdown"><div><span>{copy.price}</span><b>{money(selectedItem.price)}</b></div><div><span>{copy.cost}</span><b>−{money(selectedItem.cost)}</b></div><div><span>{copy.delivery}</span><b>−{money(selectedItem.delivery)}</b></div><div><span>{copy.ads}</span><b>−{money(selectedItem.ads)}</b></div><div><span>{copy.returns} · {selectedItem.returnRate}%</span><b>−{money(selectedItem.delivery * selectedItem.returnRate / 100)}</b></div><div className="total"><span>{copy.net}</span><b>{money(result.net)}</b></div></div><p className="radar-disclaimer">{copy.warning}. {fr ? "Ce calcul simplifié n’inclut pas les frais fixes, taxes ni coûts réels de retour. Demande et concurrence sont des hypothèses saisies manuellement." : "الحساب مبسط ولا يشمل المصاريف الثابتة والضرائب والتكلفة الفعلية للمرتجعات. الطلب والمنافسة فرضيات تُدخل يدويًا وليست بيانات سوق موثقة."}</p></>}</section></div>
  </div>;
}
