import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, ArrowUpRight, Calculator, Check, ExternalLink, Filter, Heart, Home, LayoutGrid, Megaphone, PackageSearch, RefreshCw, Search, SlidersHorizontal, Sparkles, Star, TrendingUp, UserRound, X } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Lang = "ar" | "fr";
type Trend = { id: string; title: string; url: string; publishedAt: string; approxTraffic: string | null; news: { title: string; url: string; source: string }[] };
type Opportunity = { name: string; why: string; relatedTrend: string; risk: string; confidence: "low" | "medium"; evidence: string[] };
type RadarResponse = { source: string; fetchedAt: string; items: Trend[]; aiConfigured: boolean; model?: string; opportunities: Opportunity[]; note?: string; aiError?: string };
type Screen = "home" | "discover" | "ads" | "saved" | "profile";
const money = (n: number, fr: boolean) => new Intl.NumberFormat(fr ? "fr-DZ" : "ar-DZ", { maximumFractionDigits: 0 }).format(n) + (fr ? " DA" : " دج");
const copy = {
 ar: { kicker:"ذكاء السوق الجزائري", greeting:"خلّي تجارتك أذكى", subtitle:"فرص أوضح. قرارات أسهل. من مكان واحد.", search:"ابحث عن منتج أو اتجاه...", today:"ملخص السوق", rising:"اتجاهات مرصودة", ideas:"أفكار منتجات للاختبار", seeAll:"عرض الكل", updated:"آخر تحديث", live:"بيانات مباشرة", refresh:"تحديث", discover:"اكتشف", ads:"الإعلانات", saved:"المحفوظات", profile:"حسابي", home:"الرئيسية", products:"المنتجات", filter:"الفلاتر", categories:"الفئة", all:"الكل", commerce:"تجاري محتمل", news:"أخبار / عام", opportunity:"فرصة للاستكشاف", source:"الاتجاه الأصلي", reason:"لماذا ظهرت؟", risk:"ما الذي يجب التحقق منه؟", confidence:"ثقة استكشافية", low:"منخفضة", medium:"متوسطة", high:"مرتفعة", noIdeas:"لا توجد فرضيات منتجات موثوقة لهذه الإشارات حالياً.", noTrends:"لا توجد نتائج مطابقة.", trendsTitle:"اتجاهات البحث في الجزائر", trendsNote:"الاتجاهات تعكس اهتمام البحث، ولا تثبت المبيعات أو نية الشراء.", productDetails:"تفاصيل فرصة المنتج", publicSource:"تحقق من المصدر العام", adTitle:"ذكاء الإعلانات", adSub:"مكان واحد لمتابعة الإعلانات العامة المتاحة للتاجر.", adNotReady:"ربط مصادر الإعلانات لم يُفعّل بعد", adExplain:"لن نعرض أرقام مشاهدات أو مبيعات مختلقة. عند تفعيل مصادر مصرح بها، ستظهر هنا تفاصيل الإعلان والمنصة وتاريخ الرصد والرابط الأصلي.", sourceStatus:"حالة المصدر", planned:"بانتظار الربط المصرّح به", savedTitle:"فرصك المحفوظة", savedSub:"احفظ اتجاهات وأفكار المنتجات للعودة إليها لاحقاً.", emptySaved:"لم تحفظ أي فرصة بعد.", profileTitle:"مساحة التاجر", profileSub:"DZ SPY جزء من لوحة Dzair Store، لمساعدتك على اكتشاف الفرص دون مغادرة متجرك.", margin:"حاسبة الربحية", buy:"تكلفة الشراء", sell:"سعر البيع", delivery:"التوصيل على البائع", adsCost:"الإعلانات لكل طلب", returns:"المرتجعات (%)", calc:"احسب الربح التقديري", estimated:"الربح التقديري لكل طلب", marginLabel:"هامش الربح", caveat:"حساب تقريبي حسب التكاليف المدخلة، وليس توقعاً للمبيعات.", save:"حفظ الفرصة", savedDone:"تم الحفظ", clear:"مسح الفلاتر", searchResults:"نتائج البحث", dataLimit:"ملاحظة البيانات", sourceLimit:"المعلومات المعروضة هي بيانات عامة متاحة. لا تمثل الاتجاهات مبيعات مؤكدة.", active:"نشط", menu:"التنقل", score:"درجة الثقة", showFilters:"تصفية النتائج", noSource:"مصدر غير متصل", productIdeas:"اقتراحات الذكاء الاصطناعي", explore:"ابدأ الاستكشاف" },
 fr: { kicker:"INTELLIGENCE DU MARCHÉ ALGÉRIEN", greeting:"Faites grandir votre commerce", subtitle:"Des signaux plus clairs. Des décisions plus simples.", search:"Rechercher un produit ou une tendance…", today:"Aperçu du marché", rising:"Tendances observées", ideas:"Idées de produits à tester", seeAll:"Tout voir", updated:"Dernière mise à jour", live:"Données en direct", refresh:"Actualiser", discover:"Découvrir", ads:"Publicités", saved:"Enregistrés", profile:"Profil", home:"Accueil", products:"Produits", filter:"Filtres", categories:"Catégorie", all:"Tout", commerce:"Piste commerciale", news:"Actualité / général", opportunity:"Piste à explorer", source:"Tendance d’origine", reason:"Pourquoi cette idée ?", risk:"Points à vérifier", confidence:"Confiance exploratoire", low:"Faible", medium:"Moyenne", high:"Élevée", noIdeas:"Aucune hypothèse produit suffisamment fiable pour ces signaux.", noTrends:"Aucun résultat correspondant.", trendsTitle:"Tendances de recherche en Algérie", trendsNote:"Les tendances reflètent l’intérêt de recherche, pas les ventes ni une intention d’achat prouvée.", productDetails:"Détails de la piste produit", publicSource:"Vérifier la source publique", adTitle:"Veille publicitaire", adSub:"Un espace unique pour suivre les publicités publiques accessibles.", adNotReady:"Les sources publicitaires ne sont pas encore connectées", adExplain:"Aucun chiffre de vues ou de ventes ne sera inventé. Après connexion de sources autorisées, cette page affichera les détails, la plateforme, la date d’observation et le lien d’origine.", sourceStatus:"État de la source", planned:"En attente d’une connexion autorisée", savedTitle:"Vos opportunités enregistrées", savedSub:"Enregistrez des tendances et idées produits pour les retrouver plus tard.", emptySaved:"Aucune opportunité enregistrée pour le moment.", profileTitle:"Espace commerçant", profileSub:"DZ SPY est intégré à votre tableau de bord Dzair Store pour explorer des opportunités sans quitter votre boutique.", margin:"Calculateur de rentabilité", buy:"Coût d’achat", sell:"Prix de vente", delivery:"Livraison à charge vendeur", adsCost:"Publicité par commande", returns:"Retours (%)", calc:"Estimer le bénéfice", estimated:"Bénéfice estimé par commande", marginLabel:"Marge bénéficiaire", caveat:"Estimation selon les coûts saisis, pas une prévision de ventes.", save:"Enregistrer la piste", savedDone:"Enregistré", clear:"Effacer les filtres", searchResults:"Résultats", dataLimit:"Limite des données", sourceLimit:"Les informations affichées proviennent de données publiques accessibles. Une tendance ne confirme pas des ventes.", active:"Active", menu:"Navigation", score:"Niveau de confiance", showFilters:"Filtrer les résultats", noSource:"Source déconnectée", productIdeas:"Suggestions IA", explore:"Commencer à explorer" }
};
export default function ProductRadar({ language }: { language: Lang }) {
 const fr=language==="fr", t=copy[language];
 const [data,setData]=useState<RadarResponse|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[query,setQuery]=useState(""),[screen,setScreen]=useState<Screen>("home"),[selected,setSelected]=useState<Opportunity|null>(null),[filterOpen,setFilterOpen]=useState(false),[category,setCategory]=useState("all"),[saved,setSaved]=useState<string[]>([]),[showMargin,setShowMargin]=useState(false);
 const [cost,setCost]=useState("1000"),[price,setPrice]=useState("2500"),[delivery,setDelivery]=useState("600"),[ads,setAds]=useState("250"),[returnRate,setReturnRate]=useState("10");
 const fetchData=useCallback(async()=>{setBusy(true);setError("");try{const {data:s,error:e}=await supabase.auth.getSession();if(e||!s.session?.access_token)throw new Error(fr?"Connectez-vous pour consulter DZ SPY.":"سجّل الدخول لاستخدام DZ SPY.");const response=await fetch("/api/product-radar",{headers:{Authorization:`Bearer ${s.session.access_token}`},cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||(fr?"La source de tendances est indisponible.":"مصدر الاتجاهات غير متاح الآن."));setData(payload as RadarResponse);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}},[fr]);
 useEffect(()=>{void fetchData()},[fetchData]);
 const ideas=useMemo(()=>{const source=data?.opportunities||[];return source.filter(x=>(x.name+" "+x.why+" "+x.relatedTrend).toLocaleLowerCase().includes(query.toLocaleLowerCase())&&(category==="all"||((category==="commerce")?true:false)));},[data,query,category]);
 const trends=useMemo(()=> (data?.items||[]).filter(x=>x.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())),[data,query]);
 const net=Number(price||0)-Number(cost||0)-Number(delivery||0)-Number(ads||0)-Number(delivery||0)*Math.min(100,Math.max(0,Number(returnRate||0)))/100;
 const dt=data?.fetchedAt?new Date(data.fetchedAt).toLocaleString(fr?"fr-DZ":"ar-DZ"):"—";
 const go=(s:Screen)=>{setScreen(s);setSelected(null);setFilterOpen(false)};
 const saveIdea=(idea:Opportunity)=>setSaved(old=>old.includes(idea.name)?old.filter(n=>n!==idea.name):[...old,idea.name]);
 const renderIdea=(idea:Opportunity,i:number)=><article className="dzspy-idea" key={`${idea.name}-${i}`}><div className="dzspy-idea-head"><span className="dzspy-idea-icon"><PackageSearch size={20}/></span><span className="dzspy-score">{idea.confidence==="medium"?t.medium:t.low}</span></div><h4>{idea.name}</h4><p>{idea.why}</p><div className="dzspy-evidence"><small>{t.source}</small><b>{idea.relatedTrend}</b></div><div className="dzspy-risk"><b>{t.risk}</b><span>{idea.risk}</span></div><div className="dzspy-card-actions"><button type="button" onClick={()=>setSelected(idea)}>{fr?"Détails":"التفاصيل"}<ArrowUpRight size={14}/></button><button type="button" aria-label={t.save} onClick={()=>saveIdea(idea)} className={saved.includes(idea.name)?"is-saved":""}>{saved.includes(idea.name)?<Check size={16}/>:<Heart size={16}/>}</button></div></article>;
 return <div className="ab-content dzspy-page" dir={fr?"ltr":"rtl"}>
  <header className="dzspy-header"><div className="dzspy-brand"><span className="dzspy-brand-mark"><Activity size={22}/></span><div><b>DZ <em>SPY</em></b><small>{t.kicker}</small></div></div><button className="dzspy-refresh" type="button" onClick={()=>void fetchData()} disabled={busy}><RefreshCw size={15} className={busy?"radar-spin":""}/>{t.refresh}</button></header>
  <div className="dzspy-mobile-nav" aria-label={t.menu}>{([["home",Home,t.home],["discover",LayoutGrid,t.discover],["ads",Megaphone,t.ads],["saved",Heart,t.saved],["profile",UserRound,t.profile]] as const).map(([id,Icon,label])=><button key={id} type="button" className={screen===id?"active":""} onClick={()=>go(id)}><Icon size={18}/><span>{label}</span></button>)}</div>
  {screen==="home"&&<><section className="dzspy-welcome"><div><span className="dzspy-overline">{t.kicker}</span><h2>{t.greeting}</h2><p>{t.subtitle}</p></div><div className="dzspy-orbit"><Sparkles size={30}/></div></section><label className="dzspy-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/><button type="button" onClick={()=>setFilterOpen(true)} aria-label={t.filter}><SlidersHorizontal size={18}/></button></label><section className="dzspy-stats"><article><span><TrendingUp size={17}/></span><b>{data?.items.length??"—"}</b><small>{t.rising}</small></article><article><span><Sparkles size={17}/></span><b>{data?.opportunities.length??"—"}</b><small>{t.ideas}</small></article><article><span><Activity size={17}/></span><b>{data?"DZ":"—"}</b><small>{data?t.live:t.noSource}</small></article></section><div className="dzspy-section-head"><div><h3>{t.ideas}</h3><p>{t.trendsNote}</p></div><button type="button" onClick={()=>go("discover")}>{t.seeAll}<ArrowUpRight size={14}/></button></div>{error&&<div className="dzspy-error"><AlertTriangle size={18}/><span>{error}</span></div>}{data?.aiError&&<div className="dzspy-error"><AlertTriangle size={18}/><span>{data.aiError}</span></div>}{data?.opportunities?.length? <div className="dzspy-ideas-grid">{data.opportunities.slice(0,3).map(renderIdea)}</div>:<div className="dzspy-empty"><Sparkles size={24}/><b>{busy?(fr?"Chargement des données…":"جارٍ تحميل البيانات…"):t.noIdeas}</b><p>{t.sourceLimit}</p></div>}<div className="dzspy-source-foot"><Activity size={15}/><span>{t.updated}: {dt}</span><a href={data?.source||"https://trends.google.com/trending?geo=DZ"} target="_blank" rel="noreferrer">Google Trends <ExternalLink size={13}/></a></div><section className="dzspy-calculator"><div><span className="dzspy-overline">DZ SPY · BUSINESS TOOL</span><h3><Calculator size={19}/>{t.margin}</h3><p>{t.caveat}</p></div><div className="dzspy-calc-fields">{[[t.buy,cost,setCost],[t.sell,price,setPrice],[t.delivery,delivery,setDelivery],[t.adsCost,ads,setAds],[t.returns,returnRate,setReturnRate]].map(([label,value,setter]:any)=><label key={label}><span>{label}</span><input type="number" min="0" value={value} onChange={e=>setter(e.target.value)}/></label>)}</div><button className="dzspy-primary" type="button" onClick={()=>setShowMargin(true)}>{t.calc}</button>{showMargin&&<div className="dzspy-profit"><small>{t.estimated}</small><b className={net<0?"negative":""}>{money(net,fr)}</b><span>{t.marginLabel}: {Number(price)>0?(net/Number(price)*100).toFixed(1):"0.0"}%</span></div>}</section></>}
  {screen==="discover"&&<><section className="dzspy-screen-title"><span className="dzspy-overline">DZ SPY / 01</span><h2>{t.discover}</h2><p>{t.trendsTitle}</p></section><label className="dzspy-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/><button type="button" onClick={()=>setFilterOpen(true)}><Filter size={18}/></button></label><div className="dzspy-filter-row"><span>{t.searchResults}: {ideas.length+trends.length}</span><button type="button" onClick={()=>{setCategory("all");setQuery("")}}>{t.clear}</button></div><div className="dzspy-chips">{[["all",t.all],["commerce",t.commerce],["news",t.news]] .map(([id,label])=><button key={id} type="button" className={category===id?"active":""} onClick={()=>setCategory(id)}>{label}</button>)}</div>{ideas.length>0&&<><div className="dzspy-section-head"><div><h3>{t.productIdeas}</h3></div></div><div className="dzspy-ideas-grid">{ideas.map(renderIdea)}</div></> }<div className="dzspy-section-head"><div><h3>{t.trendsTitle}</h3><p>{t.trendsNote}</p></div></div><div className="dzspy-trend-list">{trends.map(item=><article key={item.id}><span className="dzspy-trend-symbol"><TrendingUp size={18}/></span><div><b>{item.title}</b><small>{item.publishedAt?new Date(item.publishedAt).toLocaleDateString(fr?"fr-DZ":"ar-DZ"):""}{item.approxTraffic?` · ${item.approxTraffic}`:""}</small></div><a href={item.url} target="_blank" rel="noreferrer" aria-label={t.publicSource}><ExternalLink size={16}/></a></article>)}{!trends.length&&<div className="dzspy-empty">{t.noTrends}</div>}</div></>}
  {screen==="ads"&&<><section className="dzspy-screen-title"><span className="dzspy-overline">DZ SPY / 02</span><h2>{t.adTitle}</h2><p>{t.adSub}</p></section><div className="dzspy-ad-placeholder"><span><Megaphone size={30}/></span><h3>{t.adNotReady}</h3><p>{t.adExplain}</p><div><span className="dzspy-status-dot"/>{t.sourceStatus}<b>{t.planned}</b></div><small>{t.sourceLimit}</small></div></>}
  {screen==="saved"&&<><section className="dzspy-screen-title"><span className="dzspy-overline">DZ SPY / 03</span><h2>{t.savedTitle}</h2><p>{t.savedSub}</p></section>{saved.length? <div className="dzspy-ideas-grid">{(data?.opportunities||[]).filter(x=>saved.includes(x.name)).map(renderIdea)}</div>:<div className="dzspy-empty"><Heart size={26}/><b>{t.emptySaved}</b><p>{t.savedSub}</p><button type="button" className="dzspy-primary" onClick={()=>go("discover")}>{t.explore}</button></div>}</>}
  {screen==="profile"&&<><section className="dzspy-screen-title"><span className="dzspy-overline">DZ SPY / 04</span><h2>{t.profileTitle}</h2><p>{t.profileSub}</p></section><div className="dzspy-profile-card"><span><Activity size={24}/></span><div><b>DZ SPY</b><small>{fr?"Intégré au tableau de bord Dzair Store":"مدمج داخل لوحة التاجر في دزاير ستور"}</small></div><Check size={19}/></div><div className="dzspy-profile-note"><b>{t.dataLimit}</b><p>{t.sourceLimit}</p><p>{fr?"Les sources publicitaires seront ajoutées uniquement via des accès publics autorisés ou des intégrations officielles.":"ستضاف مصادر الإعلانات عبر الواجهات الرسمية أو البيانات العامة المسموح بها فقط."}</p></div></>}
  {filterOpen&&<div className="dzspy-overlay" onClick={()=>setFilterOpen(false)}><section className="dzspy-sheet" onClick={e=>e.stopPropagation()}><div className="dzspy-sheet-handle"/><header><h3>{t.showFilters}</h3><button type="button" onClick={()=>setFilterOpen(false)}><X size={18}/></button></header><b>{t.categories}</b><div className="dzspy-chips">{[["all",t.all],["commerce",t.commerce],["news",t.news]].map(([id,label])=><button key={id} type="button" className={category===id?"active":""} onClick={()=>setCategory(id)}>{label}</button>)}</div><label className="dzspy-sheet-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/></label><button className="dzspy-primary" type="button" onClick={()=>setFilterOpen(false)}>{t.searchResults}</button></section></div>}
  {selected&&<div className="dzspy-overlay" onClick={()=>setSelected(null)}><section className="dzspy-sheet dzspy-detail-sheet" onClick={e=>e.stopPropagation()}><div className="dzspy-sheet-handle"/><header><h3>{t.productDetails}</h3><button type="button" onClick={()=>setSelected(null)}><X size={18}/></button></header><span className="dzspy-detail-icon"><PackageSearch size={28}/></span><h2>{selected.name}</h2><p>{selected.why}</p><div className="dzspy-detail-block"><small>{t.source}</small><b>{selected.relatedTrend}</b></div><div className="dzspy-detail-block"><small>{t.risk}</small><p>{selected.risk}</p></div><div className="dzspy-detail-block"><small>{t.confidence}</small><b>{selected.confidence==="medium"?t.medium:t.low}</b></div>{selected.evidence?.length>0&&<div className="dzspy-detail-block"><small>{t.publicSource}</small>{selected.evidence.map(e=><span key={e}>{e}</span>)}</div>}<div className="dzspy-detail-actions"><button className="dzspy-primary" type="button" onClick={()=>saveIdea(selected)}>{saved.includes(selected.name)?<Check size={16}/>:<Heart size={16}/>} {saved.includes(selected.name)?t.savedDone:t.save}</button>{data?.items.find(x=>x.title===selected.relatedTrend)?.url&&<a href={data.items.find(x=>x.title===selected.relatedTrend)?.url} target="_blank" rel="noreferrer">{t.publicSource}<ArrowUpRight size={14}/></a>}</div><small className="dzspy-caveat">{t.sourceLimit}</small></section></div>}
  <footer className="dzspy-footer">DZ SPY · {t.sourceLimit}</footer>
 </div>;
}
